name: Publish
on: [workflow_dispatch]

jobs:
    build:
      name: Publish
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Publish
          env:
            NUGET_KEY: ${{ secrets.NUGET_KEY }}
          run: .\.github\workflows\publish.ps1
          shell: pwsh